package com.fiap.hackaton.entity.descarteEquipamento.exception;

public class DescarteEquipamentoNotFoundException extends Exception {

    public DescarteEquipamentoNotFoundException() {
        super("O equipamento n√£o foi encontrado!");
    }

}
