package com.fiap.hackaton.entity.entregaEquipamento.exception;

public class EntregaEquipamentoNotFoundException extends Exception {

    public EntregaEquipamentoNotFoundException() {
        super("A entrega n√£o foi encontrada!");
    }

}
