package com.fiap.hackaton.entity.entregaInsumo.exception;

public class EntregaInsumoNotFoundException extends Exception {

    public EntregaInsumoNotFoundException() {
        super("A entrega n√£o foi encontrada!");
    }

}
